---
- name: "Validate invocation of common role"
  ansible.builtin.assert:
    that:
      - "ansible_parent_role_names is defined"
      - "ansible_parent_role_names | default() | length > 0"
    fail_msg: "Error: The 'common' role is a internal role and cannot be invoked directly."
  tags:
    - always

- name: "Gather system user and group facts"
  ansible.builtin.getent:
    database: "{{ item }}"
  loop:
    - passwd
    - group
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"

- name: "Create system group {{ common_system_group }}"
  ansible.builtin.group:
    name: "{{ common_system_group }}"
    system: true
    state: present
  become: true
  when: common_system_group not in ansible_facts.getent_group
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"

- name: "Create system user {{ common_system_user }}"
  ansible.builtin.user:
    name: "{{ common_system_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ common_system_group }}"
    home: "{{ common_config_dir | default('/', true) }}"
    create_home: false
  become: true
  when: common_system_user not in ansible_facts.getent_passwd
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"

- name: "Download binary {{ _common_binary_basename }}"
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"
    - download
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_download"
  become: false
  delegate_to: localhost
  block:
    - name: "Create localhost binary cache path"
      ansible.builtin.file:
        path: "{{ common_local_cache_path }}"
        state: directory
        mode: 0755
      check_mode: false

    - name: "Download {{ _common_binary_basename }}"
      ansible.builtin.uri:
        url: "{{ common_binary_url }}"
        dest: "{{ common_local_cache_path }}/{{ common_binary_name | default(_common_binary_basename) }}"
        headers: "{{ _common_github_api_headers }}"
        mode: 0644
        status_code: [200, 203, 204, 206, 300, 301, 302, 303, 304, 307, 308]
        follow_redirects: all
      register: _common_download
      until: _common_download is succeeded
      retries: 5
      delay: 2
      # run_once: true  # <-- this can't be set due to multi-arch support
      check_mode: false

    - name: "Verify checksum of {{ _common_binary_basename }}"
      run_once: true
      check_mode: false
      when: (common_checksums_url)
      block:
        - name: "Fetch checksum list for {{ _common_binary_basename }}"
          ansible.builtin.uri:
            url: "{{ common_checksums_url }}"
            headers: "{{ _common_github_api_headers }}"
            method: GET
            return_content: true
            status_code: [200, 203, 204, 206, 300, 301, 302, 303, 304, 307, 308]
            follow_redirects: all
          register: _common_binary_checksums_raw

        - name: "Parse checksum list for {{ _common_binary_basename }}"
          ansible.builtin.set_fact:
            _common_binary_checksums: "{{ dict(_common_binary_checksums_raw.content.splitlines()
                                        | map('regex_findall', '^([a-fA-F0-9]+)\\s+(.+)$') | map('flatten') | map('reverse')) }}"

        - name: "Calculate checksum of {{ _common_binary_basename }}"
          ansible.builtin.stat:
            path: "{{ common_local_cache_path }}/{{ common_binary_name | default(_common_binary_basename) }}"
            checksum_algorithm: sha256
            get_checksum: true
          register: _common_binary_checksum

        - name: "Verify correct checksum of {{ _common_binary_basename }}"
          ansible.builtin.assert:
            that: _common_binary_checksum.stat.checksum == _common_binary_checksums[_common_binary_basename]
            success_msg: "{{ _common_binary_basename }} checksum verified successfully"
            fail_msg: "{{ _common_binary_basename }} checksum mismatch"

    - name: "Unpack binary archive {{ _common_binary_basename }}"
      ansible.builtin.unarchive:
        src: "{{ common_local_cache_path }}/{{ _common_binary_basename }}"
        dest: "{{ common_local_cache_path }}"
        mode: 0755
        list_files: true
        extra_opts: "{{ common_binary_unarchive_opts | default(omit, true) }}"
      check_mode: false
      throttle: 1  # see prometheus-community/ansible#457
      when: _common_binary_basename is search('\.zip$|\.tar\.gz$')

- name: "Check existence of binary install dir"
  ansible.builtin.stat:
    path: "{{ common_binary_install_dir }}"
  register: _common_binary_install_dir

- name: "Make sure binary install dir exists"
  ansible.builtin.file:
    path: "{{ common_binary_install_dir }}"
    mode: 0755
    owner: root
    group: root
  become: true
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"
  when: not _common_binary_install_dir.stat.exists

- name: "Propagate binaries"
  ansible.builtin.copy:
    src: "{{ common_local_cache_path }}/{{ item }}"
    dest: "{{ common_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
  loop: "{{ common_binaries }}"
  become: true
  notify:
    - "{{ ansible_parent_role_names | first }} : Restart {{ common_service_name }}"
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"