---
# The argument_spec provided to AnsibleModule defines the supported arguments for a module, as well as their type, defaults and more.
# In this case it provides this role dependencies for Ansible Galaxy listing info.
galaxy_info:
  author: "Prometheus Community"
  description: "Prometheus monitoring system configuration and management"
  license: "Apache"
  min_ansible_version: "2.12"
  platforms:
    - name: "Ubuntu"
      versions:
        - "jammy"
        - "noble"
    - name: "Debian"
      versions:
        - "bullseye"
    - name: "EL"
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - "monitoring"
    - "prometheus"
    - "metrics"
    - "alerts"
    - "alerting"
    - "molecule"
    - "cloud"